apiVersion: v1
kind: Secret
metadata:
  name: apirest-secret
  namespace: apirest-ns
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=  # base64 encoded 'postgres'
  SPRING_DATASOURCE_PASSWORD: YWNhZGVteWphdmE=  # base64 encoded 'password'
  JWT_SECRET_KEY: c2VjcmV0S2V5MTIzNDU2Nzg5MA==  # base64 encoded 'secretKey1234567890'